name: CI - Build and Push Docker Images
on:
  push:
   branches:
      - main
jobs:
  docker:
    runs-on: 	ubuntu-latest	
    env:
      IMAGE_NAME: edee_portfolio
      IMAGE_TAG: 1.2.0
      DOCKER_HUB_REGISTRY: docker.io/baayhacker

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build de l'image Docker
        run: docker build -t $DOCKER_HUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

      - name: Push image Docker
        run: docker push $DOCKER_HUB_REGISTRY/$IMAGE_NAME:$IMAGE_TAG